// ============================================================================
// View Registry — Single source of truth for all views
// ============================================================================
// To add a new view:
//   1. Create the .vue file in src/views/
//   2. Add an entry below
//   3. (Optional) Add props/events config in App.vue's viewPropsConfig/viewEventsConfig
//
// Fields:
//   id            — unique view identifier (matches currentView value)
//   component     — dynamic import function
//   label         — display name in DevNavBar/archive
//   status        — 'active' | 'archived' | 'system'
//   section       — DevNavBar section key (see sections.js) or null
//   hideLogo      — true = hide global logo (default true; most views hide it)
//   slug          — URL hash slug if different from id
//   keyPrefix     — if set, component :key = `${keyPrefix}-${sessionKey}`
//   refName       — template ref name (for views with internal navigation)
//   nav           — navigation behavior in handleDevNavigate (null = simple assignment)
//   matchPrefix   — for prefix-based component resolution (e.g. 'settings-ai')
// ============================================================================

// -- Helpers for generating sub-view entries ---------------------------------

const aiScreenSuffixes = [
  '', '-new', '-presets', '-preview', '-choose-products',
  '-generation', '-add-products', '-text-presets', '-text-preview', '-text-generation',
]

const aiV2ScreenSuffixes = [
  ...aiScreenSuffixes, '-generation-product', '-workflow-presets', '-workflow-editor', '-workflow-generation',
]

function generateAiSubViews(baseId, component, label, section) {
  const suffixes = baseId.includes('-v2') ? aiV2ScreenSuffixes : aiScreenSuffixes
  return suffixes.map(suffix => ({
    id: `${baseId}${suffix}`,
    component,
    label: suffix ? `${label} (${suffix.slice(1)})` : label,
    status: 'active',
    section,
    hideLogo: true,
  }))
}

function generateSettingsAiSubViews(baseId) {
  const suffixes = baseId.includes('-v2') ? aiV2ScreenSuffixes : aiScreenSuffixes
  return suffixes.map(suffix => ({
    id: `${baseId}${suffix}`,
    component: () => import('../views/SettingsView.vue'),
    label: `Settings AI ${suffix || 'list'}`,
    status: 'active',
    section: null,
    hideLogo: true,
    matchPrefix: baseId,
  }))
}

// -- View definitions --------------------------------------------------------

// System views
const systemViews = [
  {
    id: 'apps',
    component: () => import('../views/AppsView.vue'),
    label: 'Apps',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'apps',
  },
  {
    id: 'opticube',
    component: () => import('../opticube/OpticubeStartView.vue'),
    label: 'OptiCube',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'opticube',
    matchPrefix: 'opticube',
    hideInNav: true,
  },
  {
    id: 'opticube-design-guide',
    component: () => import('../opticube/OpticubeDesignGuideView.vue'),
    label: 'Design Guide',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'opticube',
    slug: 'opticube-design-guide',
    hideInNav: true,
  },
  {
    id: 'opticube-registration',
    component: () => import('../opticube/OpticubeRegistrationView.vue'),
    label: 'Registration',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'opticube',
    slug: 'opticube-registration',
    keyPrefix: 'oc-reg',
    hideInNav: true,
  },
  {
    id: 'opticube-onboarding',
    component: () => import('../opticube/OpticubeOnboardingView.vue'),
    label: 'Onboarding',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'opticube',
    slug: 'opticube-onboarding',
    keyPrefix: 'oc-onb',
    refName: 'opticubeOnboardingRef',
    hideInNav: true,
  },
  {
    id: 'picbear',
    component: () => import('../picbear/PicbearAppView.vue'),
    label: 'Picbear',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'picbear',
    matchPrefix: 'picbear',
  },
  {
    id: 'conversionlift',
    component: () => import('../conversionlift/ConversionLiftStartView.vue'),
    label: 'ConversionLift',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    matchPrefix: 'conversionlift',
  },
  {
    id: 'conversionlift-design-guide',
    component: () => import('../conversionlift/ConversionLiftDesignGuideView.vue'),
    label: 'Design Guide',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'conversionlift-design-guide',
    hideInNav: true,
  },
  {
    id: 'cl-flow-1',
    component: () => import('../conversionlift/Flow1View.vue'),
    label: 'Flow A · Assistant-led',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-1',
    hideInNav: true,
  },
  {
    id: 'cl-flow-2',
    component: () => import('../conversionlift/Flow2View.vue'),
    label: 'Flow B · Type-first',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-2',
    hideInNav: true,
  },
  {
    id: 'cl-flow-3',
    component: () => import('../conversionlift/Flow3View.vue'),
    label: 'Flow C · Generate-first',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-3',
    hideInNav: true,
  },
  {
    id: 'cl-flow-4',
    component: () => import('../conversionlift/Flow4View.vue'),
    label: 'Flow D · Assistant-led',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-4',
    hideInNav: true,
  },
  {
    id: 'cl-flow-5',
    component: () => import('../conversionlift/Flow5View.vue'),
    label: 'Flow E · Assistant-led',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-5',
    hideInNav: true,
  },
  {
    id: 'cl-flow-6',
    component: () => import('../conversionlift/Flow6View.vue'),
    label: 'Flow F · Assistant-led',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-flow-6',
    hideInNav: true,
  },
  {
    id: 'cl-scope-1',
    component: () => import('../conversionlift/Scope1View.vue'),
    label: 'Scope · List + filters',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-scope-1',
    hideInNav: true,
  },
  {
    id: 'cl-scope-2',
    component: () => import('../conversionlift/Scope2View.vue'),
    label: 'Scope · Visual grid',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-scope-2',
    hideInNav: true,
  },
  {
    id: 'cl-scope-3',
    component: () => import('../conversionlift/Scope3View.vue'),
    label: 'Scope · Rule segment',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-scope-3',
    hideInNav: true,
  },
  {
    id: 'cl-scope-4',
    component: () => import('../conversionlift/Scope4View.vue'),
    label: 'Scope · Rule + fine-tune',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-scope-4',
    hideInNav: true,
  },
  {
    id: 'cl-audience',
    component: () => import('../conversionlift/AudienceView.vue'),
    label: 'Audience · Segments',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-audience',
    hideInNav: true,
  },
  {
    id: 'cl-home-b',
    component: () => import('../conversionlift/HomeBView.vue'),
    label: 'Home (B)',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-home-b',
    hideInNav: false,
  },
  {
    id: 'cl-projects',
    component: () => import('../conversionlift/ProjectsView.vue'),
    label: 'Variables',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-projects',
    hideInNav: true,
  },
  {
    id: 'cl-project',
    component: () => import('../conversionlift/ProjectDetailView.vue'),
    label: 'Variable detail',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-project',
    hideInNav: true,
  },
  {
    id: 'cl-abtests',
    component: () => import('../conversionlift/ABTestsView.vue'),
    label: 'A/B tests',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-abtests',
    hideInNav: true,
  },
  {
    id: 'cl-abtest',
    component: () => import('../conversionlift/ABTestDetailView.vue'),
    label: 'A/B test detail',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-abtest',
    hideInNav: true,
  },
  {
    id: 'cl-abtest-setup',
    component: () => import('../conversionlift/ABTestSetupView.vue'),
    label: 'A/B test setup',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-abtest-setup',
    hideInNav: true,
  },
  {
    id: 'cl-recommendation',
    component: () => import('../conversionlift/RecommendationView.vue'),
    label: 'Recommendation detail',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-recommendation',
    hideInNav: true,
  },
  {
    id: 'cl-generate',
    component: () => import('../conversionlift/GenerateView.vue'),
    label: 'Generate · Bulk progress',
    status: 'system',
    section: null,
    hideLogo: true,
    product: 'conversionlift',
    slug: 'cl-generate',
    hideInNav: true,
  },
  {
    id: 'dev-start',
    component: () => import('../views/DevStartView.vue'),
    label: 'Dev Start',
    status: 'system',
    section: null,
    hideLogo: true,
  },
  {
    id: 'design-guide',
    component: () => import('../views/DesignGuideView.vue'),
    label: 'Design Guide',
    status: 'system',
    section: null,
    hideLogo: true,
  },
  {
    id: 'editor',
    component: () => import('../views/EditorView.vue'),
    label: 'Editor',
    status: 'system',
    section: null,
    hideLogo: true,
  },
  {
    id: 'settings',
    component: () => import('../views/SettingsView.vue'),
    label: 'Settings',
    status: 'system',
    section: null,
    hideLogo: true,
    matchPrefix: 'settings',
  },
  {
    id: 'subscription-cl-a',
    component: () => import('../views/SubscriptionConversionLiftView.vue'),
    label: 'CL · Status card',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
  {
    id: 'subscription-credit-buy',
    component: () => import('../views/SubscriptionCreditBuyView.vue'),
    label: 'CL · Credit buy',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
  {
    id: 'subscription-cl-d',
    component: () => import('../views/SubscriptionConversionLiftView.vue'),
    label: 'CL · Summary card',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
  {
    id: 'subscription-cl-tabs',
    component: () => import('../views/SubscriptionTabbedView.vue'),
    label: 'CL · Product tabs',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
  {
    id: 'subscription-cl-usage',
    component: () => import('../views/SubscriptionUsageView.vue'),
    label: 'CL · Account & usage',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
  {
    id: 'subscription-cl-combined',
    component: () => import('../views/SubscriptionCombinedView.vue'),
    label: 'CL · Combined card',
    status: 'active',
    section: 'subscription',
    hideLogo: true,
  },
]

// Registration & Onboarding
const registrationViews = [
  {
    id: 'registration',
    component: () => import('../views/RegistrationView.vue'),
    label: 'Registration',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg',
    nav: { sessionReset: true, flowSelected: true, mobileOnboardingVariant: null, useHuDesktopFlow: false },
  },
  {
    id: 'registration-hu',
    component: () => import('../views/RegistrationHuView.vue'),
    label: 'Registration (HU)',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg-hu',
    nav: { sessionReset: true, flowSelected: true, mobileOnboardingVariant: null, useHuDesktopFlow: true },
  },
  {
    id: 'registration-mobile',
    component: () => import('../views/RegistrationMobileView.vue'),
    label: 'Registration (Mobile)',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg-mobile',
    nav: { sessionReset: true, flowSelected: true, mobileOnboardingVariant: 'en', useHuDesktopFlow: false },
  },
  {
    id: 'registration-mobile-hu',
    component: () => import('../views/RegistrationMobileHuView.vue'),
    label: 'Registration (Mobile HU)',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg-mobile-hu',
    nav: { sessionReset: true, flowSelected: true, mobileOnboardingVariant: 'hu', useHuDesktopFlow: false },
  },
  {
    id: 'login',
    component: () => import('../views/LoginView.vue'),
    label: 'Login',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'login',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'shopify-account-choice',
    component: () => import('../views/ShopifyAccountChoiceView.vue'),
    label: 'Shopify Account Choice',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'shopify-choice',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'shopify' },
  },
  {
    id: 'registration-v1',
    component: () => import('../views/RegistrationV1View.vue'),
    label: 'Registration V1',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg-v1',
  },
  {
    id: 'registration-v2',
    component: () => import('../views/RegistrationV2View.vue'),
    label: 'Registration V2',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'reg-v2',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'onboarding',
    component: () => import('../views/OnboardingView.vue'),
    label: 'Onboarding',
    status: 'active',
    section: null,
    hideLogo: false, // Logo IS shown for onboarding
    keyPrefix: 'onb',
    refName: 'onboardingRef',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'onboarding-hu',
    component: () => import('../views/OnboardingHuView.vue'),
    label: 'Onboarding (HU)',
    status: 'active',
    section: null,
    hideLogo: false,
    keyPrefix: 'onb-hu',
    refName: 'onboardingHuRef',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'onboarding-mobile',
    component: () => import('../views/OnboardingMobileView.vue'),
    label: 'Onboarding (Mobile)',
    status: 'active',
    section: null,
    hideLogo: false,
    keyPrefix: 'onb-mobile',
    refName: 'onboardingMobileRef',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'onboarding-mobile-hu',
    component: () => import('../views/OnboardingMobileHuView.vue'),
    label: 'Onboarding (Mobile HU)',
    status: 'active',
    section: null,
    hideLogo: false,
    keyPrefix: 'onb-mobile-hu',
    refName: 'onboardingMobileHuRef',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'task-creation',
    component: () => import('../views/TaskCreationView.vue'),
    label: 'Home Agentic',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'task',
    refName: 'taskCreationRef',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
]

// Home views
const homeViews = [
  {
    id: 'home-chat-start',
    component: () => import('../views/HomeChatStartView.vue'),
    label: 'Home (chat start)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-chat-start',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-old',
    component: () => import('../views/HomeView.vue'),
    label: 'Home (dashboard)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-old',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-conversion-lift',
    component: () => import('../views/HomeConversionLiftView.vue'),
    label: 'Home (Conversion Lift)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-conversion-lift',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'conversion-lift-products',
    component: () => import('../views/ConversionLiftProductsView.vue'),
    label: 'Sub-sidebar',
    status: 'active',
    section: 'conversionLift',
    hideLogo: true,
    nav: { sessionReset: true },
  },
  {
    id: 'cl-menu-tabs',
    component: () => import('../views/ConversionLiftTabsView.vue'),
    label: 'Top tabs',
    status: 'active',
    section: 'conversionLift',
    hideLogo: true,
    nav: { sessionReset: true },
  },
  {
    id: 'conversion-lift-product',
    component: () => import('../views/ConversionLiftProductPageView.vue'),
    label: 'Conversion Lift · AI Texts & Images',
    status: 'active',
    section: null,
    hideLogo: true,
    nav: { sessionReset: true },
  },
  {
    id: 'conversion-lift-catalog',
    component: () => import('../views/ConversionLiftProductPageView.vue'),
    label: 'Conversion Lift · Product catalog',
    status: 'active',
    section: null,
    hideLogo: true,
    nav: { sessionReset: true },
  },
  {
    id: 'conversion-lift-reco',
    component: () => import('../views/ConversionLiftProductPageView.vue'),
    label: 'Conversion Lift · AI recommendations',
    status: 'active',
    section: null,
    hideLogo: true,
    nav: { sessionReset: true },
  },
  {
    id: 'cl-menu-flyout',
    component: () => import('../views/HomeConversionLiftView.vue'),
    label: 'Flyout menu',
    status: 'active',
    section: 'conversionLift',
    hideLogo: true,
    keyPrefix: 'cl-menu-flyout',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-todays-plan',
    component: () => import('../views/HomeTodaysPlanView.vue'),
    label: "Home (today's plan)",
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-todays-plan',
    slug: 'agentic/home',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'experiences-list',
    component: () => import('../views/ExperiencesListView.vue'),
    label: 'Experiences',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'experiences-list',
    slug: 'agentic/experiences',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'insights-v1',
    component: () => import('../views/InsightsV1View.vue'),
    label: 'Insights (v1 dashboard)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'insights-v1',
    slug: 'agentic/insights',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'insights-v2',
    component: () => import('../views/InsightsV2View.vue'),
    label: 'Insights (v2 agent)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'insights-v2',
    slug: 'agentic/insights-v2',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'agentic-analytics',
    component: () => import('../views/AgenticAnalyticsView.vue'),
    label: 'Agentic — Analytics (detailed)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'agentic-analytics',
    slug: 'agentic/analytics',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'insights-v3',
    component: () => import('../views/InsightsV3View.vue'),
    label: 'Agentic — Analytics (funnel)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'agentic-analytics-funnel',
    slug: 'agentic/analytics-funnel',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-alerts',
    component: () => import('../views/HomeAlertsView.vue'),
    label: 'Home (alerts)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-alerts',
    slug: 'home-alerts',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-alerts-v3',
    component: () => import('../views/HomeAlertsV3View.vue'),
    label: 'Home (alerts v3)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-alerts-v3',
    slug: 'home-alerts-v3',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v9',
    component: () => import('../views/HomeInsightsV9View.vue'),
    label: 'Home (Insights V9)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v9',
    slug: 'home-insights-v9',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-heartbeat-setup',
    component: () => import('../views/HomeInsightsV11View.vue'),
    label: 'Home (Heartbeat — setup)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-heartbeat-setup',
    slug: 'home-heartbeat-setup',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-no-domain',
    component: () => import('../views/HomeInsightsV14View.vue'),
    label: 'No domain',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-no-domain',
    slug: 'home-no-domain',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-heartbeat-offline',
    component: () => import('../views/HomeInsightsV12View.vue'),
    label: 'Home (Heartbeat — no signal 24h)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-heartbeat-offline',
    slug: 'home-heartbeat-offline',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-heartbeat-quiet',
    component: () => import('../views/HomeInsightsV13View.vue'),
    label: 'Home (Heartbeat — 0 live, healthy)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-heartbeat-quiet',
    slug: 'home-heartbeat-quiet',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-archive',
    component: () => import('../views/HomeInsightsArchiveView.vue'),
    label: 'Home Insights — Archive',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-archive',
    slug: 'home-insights-archive',
  },
  {
    id: 'home-insights-v2',
    component: () => import('../views/HomeInsightsV2View.vue'),
    label: 'Home (Insights V2)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v2',
    slug: 'home-insights-v2',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v3',
    component: () => import('../views/HomeInsightsV3View.vue'),
    label: 'Home (Insights V3)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v3',
    slug: 'home-insights-v3',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v4',
    component: () => import('../views/HomeInsightsV4View.vue'),
    label: 'Home (Insights V4)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v4',
    slug: 'home-insights-v4',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v5',
    component: () => import('../views/HomeInsightsV5View.vue'),
    label: 'Home (Insights V5)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v5',
    slug: 'home-insights-v5',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v6',
    component: () => import('../views/HomeInsightsV6View.vue'),
    label: 'Home (Insights V6)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v6',
    slug: 'home-insights-v6',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v7',
    component: () => import('../views/HomeInsightsV7View.vue'),
    label: 'Home (Insights V7)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v7',
    slug: 'home-insights-v7',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v8',
    component: () => import('../views/HomeInsightsV8View.vue'),
    label: 'Home (Insights V8)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v8',
    slug: 'home-insights-v8',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-insights-v10',
    component: () => import('../views/HomeInsightsV10View.vue'),
    label: 'Home (Insights V10)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-insights-v10',
    slug: 'home-insights-v10',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-old-legacy',
    component: () => import('../views/HomeOldView.vue'),
    label: 'Home (legacy)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-old-legacy',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-heartbeat',
    component: () => import('../views/HomeHeartbeatView.vue'),
    label: 'Home Heartbeat',
    status: 'archived',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-heartbeat',
  },
  {
    id: 'chat-create-popup-v1',
    component: () => import('../views/ChatCreatePopupV1View.vue'),
    label: 'Chat_Create-popup_V1',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'chat-create-popup-v1',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'chat-create-popup-v3',
    component: () => import('../views/ChatCreatePopupV3View.vue'),
    label: 'Chat_Create-popup_V3',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'chat-create-popup-v3',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'chat-create-popup-v2',
    component: () => import('../views/ChatCreatePopupV2View.vue'),
    label: 'Chat_Create-popup_V2',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'chat-create-popup-v2',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-old-v2',
    component: () => import('../views/HomeOldV2View.vue'),
    label: 'Home Old',
    status: 'archived',
    section: null,
    hideLogo: false,
  },
  {
    id: 'home-with-review',
    component: () => import('../views/HomeWithReviewView.vue'),
    label: 'Home (Review)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-with-review',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-chat-versions',
    component: () => import('../views/HomeChatVersionsView.vue'),
    label: 'Chat Versions',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'home-chat-left',
    component: () => import('../views/HomeChatLeftView.vue'),
    label: 'Chat Left',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'home-onboarding',
    component: () => import('../views/HomeOnboardingView.vue'),
    label: 'Home Onboarding',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-onboarding',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'first-campaign-created',
    component: () => import('../views/FirstCampaignCreatedView.vue'),
    label: 'First campaign created',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'first-campaign-created',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'home-onboarding-v1',
    component: () => import('../views/HomeOnboardingV1View.vue'),
    label: 'Home Onboarding V1',
    status: 'archived',
    section: null,
    hideLogo: false,
    keyPrefix: 'home-onboarding-v1',
  },
  {
    id: 'home-onboarding-with-reco',
    component: () => import('../views/HomeOnboardingWithRecoView.vue'),
    label: 'Home + Reco',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-onboarding-with-reco',
  },
  {
    id: 'home-onboarding-with-reco-v1',
    component: () => import('../views/HomeOnboardingWithRecoV1View.vue'),
    label: 'Home Onboarding + Reco V1',
    status: 'archived',
    section: null,
    hideLogo: false,
    keyPrefix: 'home-onboarding-with-reco-v1',
  },
  {
    id: 'home-onboarding-review',
    component: () => import('../views/HomeOnboardingReviewView.vue'),
    label: 'Home Review',
    status: 'active',
    section: 'home',
    hideLogo: true,
  },
  {
    id: 'home-agentic',
    component: () => import('../views/HomeAgenticView.vue'),
    label: 'Home Agentic',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-agentic',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-agentic-v5',
    component: () => import('../views/HomeAgenticV5View.vue'),
    label: 'Home Agentic V5 (Campaign-attached)',
    status: 'active',
    section: 'home',
    hideLogo: true,
    keyPrefix: 'home-agentic-v5',
    nav: { sessionReset: true, flowSelected: true, clearWizardMessage: true },
  },
  {
    id: 'home-onboarding-wizard',
    component: () => import('../views/HomeOnboardingWizardView.vue'),
    label: 'Home Wizard',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'home-onboarding-wizard',
    refName: 'homeOnboardingWizardRef',
  },
  {
    id: 'countdown-units',
    component: () => import('../views/CountdownUnitsView.vue'),
    label: 'Countdown — unit display',
    status: 'active',
    section: null,
    hideLogo: true,
  },
]

// Wizard views
const wizardViews = [
  {
    id: 'public-wizard',
    component: () => import('../views/PublicWizardView.vue'),
    label: 'Public Wizard',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'public-wizard',
    refName: 'publicWizardRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'public-wizard', clearWizardMessage: true, extraState: { publicWizardStep: 'url' } },
  },
  {
    id: 'public-wizard-v2',
    component: () => import('../views/PublicWizardV2View.vue'),
    label: 'OptiMonk Agentic',
    status: 'active',
    section: null,
    hideLogo: true,
    slug: 'agentic',
    keyPrefix: 'public-wizard-v2',
    refName: 'publicWizardV2Ref',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'public-wizard-v2', clearWizardMessage: true, extraState: { publicWizardStep: 'url' } },
  },
  {
    id: 'public-wizard-v3',
    component: () => import('../views/PublicWizardV3View.vue'),
    label: 'Public Wizard V3',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'public-wizard-v3',
    refName: 'publicWizardV3Ref',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'public-wizard-v3', clearWizardMessage: true, extraState: { publicWizardStep: 'url' } },
  },
  {
    id: 'optimonk-agentic',
    component: () => import('../views/OptiMonkAgenticView.vue'),
    label: 'OptiMonk Agentic',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'optimonk-agentic',
    refName: 'optimonkAgenticRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'optimonk-agentic', clearWizardMessage: true },
  },
  {
    id: 'optimonk-agentic-v2',
    component: () => import('../views/OptiMonkAgenticV2View.vue'),
    label: 'OptiMonk Agentic V2',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'optimonk-agentic-v2',
    refName: 'optimonkAgenticV2Ref',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'optimonk-agentic-v2', clearWizardMessage: true },
  },
  {
    id: 'wizard-flow',
    component: () => import('../views/WizardFlowView.vue'),
    label: 'Wizard Flow',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-flow',
    refName: 'wizardFlowRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'wizard', clearWizardMessage: true, extraState: { wizardFlowStep: 'url' } },
  },
  {
    id: 'wizard',
    component: () => import('../views/WizardView.vue'),
    label: 'Wizard',
    status: 'active',
    section: null,
    hideLogo: false,
    keyPrefix: 'wizard',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-analysis',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Wizard Flow',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-analysis',
    refName: 'wizardAnalysisRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'wizard', defaultWizardMessage: 'Demo website analysis' },
  },
  {
    id: 'wizard-analysis-no-chat',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Wizard Flow (no chat)',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-analysis-no-chat',
    nav: { sessionReset: true, flowSelected: true, defaultWizardMessage: 'Demo website analysis' },
  },
  {
    id: 'wizard-style',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Wizard Style',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-style',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-quicktune',
    component: () => import('../views/TemplatesV2QuicktuneView.vue'),
    label: 'Wizard Quicktune',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-quicktune',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation V1',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation-v2',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation V2',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation-v2',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation-v3',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation V3',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation-v3',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation-v4',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation V4',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation-v4',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation-v5',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation V5',
    status: 'archived',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation-v5',
    nav: { sessionReset: true, flowSelected: true },
  },
  {
    id: 'wizard-recommendation-public-v2',
    component: () => import('../views/WizardAnalysisView.vue'),
    label: 'Recommendation (Public V2)',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'wizard-recommendation-public-v2',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'public-wizard-v2', extraState: { publicWizardStep: 'wizard-recommendation-public-v2' } },
  },
]

// Campaigns
const campaignViews = [
  {
    id: 'campaigns',
    component: () => import('../views/CampaignsView.vue'),
    label: 'Campaigns',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  {
    id: 'campaigns-v2',
    component: () => import('../views/CampaignsV2View.vue'),
    label: 'Campaigns V2',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  {
    id: 'campaigns-v3',
    component: () => import('../views/CampaignsV3View.vue'),
    label: 'Campaigns',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  {
    id: 'campaigns-v3-tagging',
    component: () => import('../views/CampaignsV3TaggingView.vue'),
    label: 'Campaigns (Tagging)',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  {
    id: 'campaigns-v3-taggingv2',
    component: () => import('../views/CampaignsV3TaggingV2View.vue'),
    label: 'Campaigns (Tagging V2)',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  {
    id: 'campaigns-empty',
    component: () => import('../views/CampaignsEmptyView.vue'),
    label: 'Campaigns (empty)',
    status: 'active',
    section: 'campaigns',
    hideLogo: true,
  },
  // ── Audience ──
  {
    id: 'audience',
    component: () => import('../views/AudienceView.vue'),
    label: 'Audience',
    status: 'active',
    section: 'audience',
    hideLogo: true,
  },
  {
    id: 'audience-profile',
    component: () => import('../views/AudienceProfileView.vue'),
    label: 'Audience Profile',
    status: 'active',
    section: 'audience',
    hideLogo: true,
  },
  {
    id: 'new-campaign',
    component: () => import('../views/NewCampaignView.vue'),
    label: 'New Campaign',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-loading',
    component: () => import('../views/PpoLoadingView.vue'),
    label: 'SPP Loading',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-loading-summary',
    component: () => import('../views/PpoLoadingView.vue'),
    label: 'SPP Loading (Summary)',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-loading-badge',
    component: () => import('../views/PpoLoadingView.vue'),
    label: 'SPP Loading (Badge)',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-no-product-page',
    component: () => import('../views/PpoNoProductPageView.vue'),
    label: 'SPP — No Product Page',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'campaign-page-v1',
    component: () => import('../views/CampaignPageV1View.vue'),
    label: 'Campaign Page (A/B — comparison)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail',
  },
  {
    id: 'campaign-detail-segment-size',
    component: () => import('../views/CampaignDetailSegmentSizeView.vue'),
    label: 'Campaign Page (Segment Size)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-segment-size',
  },
  {
    id: 'campaign-detail-tagged',
    component: () => import('../views/CampaignDetailTaggedView.vue'),
    label: 'Campaign Page (Tagged)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-tagged',
  },
  {
    id: 'campaign-page-survey',
    component: () => import('../views/CampaignPageSurveyView.vue'),
    label: 'Campaign Page (Survey)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-survey',
  },
  {
    id: 'campaign-page-alerts-banner',
    component: () => import('../views/CampaignPageAlertsBannerView.vue'),
    label: 'Campaign Page (alerts — banner)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-alerts-banner',
  },
  {
    id: 'campaign-page-alerts-chip',
    component: () => import('../views/CampaignPageAlertsChipView.vue'),
    label: 'Campaign Page (alerts — chip)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-alerts-chip',
  },
  {
    id: 'campaign-page-insight-v1',
    component: () => import('../views/CampaignPageInsightV1View.vue'),
    label: 'Campaign Page (Insight V1)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v1',
  },
  {
    id: 'campaign-page-insight-v2',
    component: () => import('../views/CampaignPageInsightV2View.vue'),
    label: 'Campaign Page (Insight V2)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-insight-v2',
  },
  {
    id: 'campaign-page-insight-v3',
    component: () => import('../views/CampaignPageInsightV3View.vue'),
    label: 'Campaign Page (Insight V3)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v3',
  },
  {
    id: 'campaign-page-insight-v4',
    component: () => import('../views/CampaignPageInsightV4View.vue'),
    label: 'Campaign Page (Insight V4)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v4',
  },
  {
    id: 'campaign-page-insight-v5',
    component: () => import('../views/CampaignPageInsightV5View.vue'),
    label: 'Campaign Page (Insight V5)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v5',
  },
  {
    id: 'campaign-page-insight-v6',
    component: () => import('../views/CampaignPageInsightV6View.vue'),
    label: 'Campaign Page (Insight V6)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v6',
  },
  {
    id: 'campaign-page-insight-v7',
    component: () => import('../views/CampaignPageInsightV7View.vue'),
    label: 'Campaign Page (Insight V7)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v7',
  },
  {
    id: 'campaign-page-insight-v8',
    component: () => import('../views/CampaignPageInsightV8View.vue'),
    label: 'Campaign Page (Insight V8)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-insight-v8',
  },
  {
    id: 'campaign-page-v2',
    component: () => import('../views/CampaignPageV2View.vue'),
    label: 'Campaign Page V2',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-v2',
  },
  {
    id: 'campaign-page-v1-pivoted',
    component: () => import('../views/CampaignPageV1View.vue'),
    label: 'Campaign Page (A/B — pivoted)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-pivoted',
  },
  {
    id: 'campaign-page-v1-bar-chart',
    component: () => import('../views/CampaignPageV1View.vue'),
    label: 'Campaign Page (A/B — bar chart)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-bar-chart',
  },
  {
    id: 'campaign-page-v2-mark',
    component: () => import('../views/CampaignPageV2MarkView.vue'),
    label: 'Campaign Page V2 (Mark)',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-v2-mark',
  },
  {
    id: 'campaign-page-single',
    component: () => import('../views/CampaignPageSingleView.vue'),
    label: 'Campaign Page (no A/B)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-detail-single',
  },
  {
    id: 'campaign-page-single-v2',
    component: () => import('../views/CampaignPageSingleV2View.vue'),
    label: 'Campaign Page (no A/B) V2',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'campaign-detail-single-v2',
  },
  {
    id: 'campaign-page-with-review',
    component: () => import('../views/CampaignPageWithReviewView.vue'),
    label: 'Campaign + Review',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
    slug: 'campaign-new',
  },
  {
    id: 'campaign-review',
    component: () => import('../views/CampaignReviewView.vue'),
    label: 'Campaign Review',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'campaign-settings-step',
    component: () => import('../views/CampaignSettingsStepView.vue'),
    label: 'Campaign Settings (step)',
    status: 'active',
    section: 'campaignPage',
    hideLogo: true,
  },
]

// Analytics
const analyticsViews = [
  {
    id: 'analytics-v1',
    component: () => import('../views/AnalyticsV1View.vue'),
    label: 'Analytics V1',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'analytics-v2',
    component: () => import('../views/AnalyticsV2View.vue'),
    label: 'Analytics V2',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'analytics-v3',
    component: () => import('../views/AnalyticsV3View.vue'),
    label: 'Analytics V3',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'analytics-v4',
    component: () => import('../views/AnalyticsV4View.vue'),
    label: 'Analytics',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics',
  },
  {
    id: 'analytics-v4-opps-v2',
    component: () => import('../views/AnalyticsV4OpportunitiesV2View.vue'),
    label: 'Analytics (Opps V2)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-opps-v2',
  },
  {
    id: 'analytics-v4-opps-v3',
    component: () => import('../views/AnalyticsV4OpportunitiesV3View.vue'),
    label: 'Analytics (Opps V3)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-opps-v3',
  },
  {
    id: 'analytics-v4-purchase',
    component: () => import('../views/AnalyticsV4View.vue'),
    label: 'Analytics (Purchase)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-purchase',
  },
  {
    id: 'analytics-v4-add-to-cart',
    component: () => import('../views/AnalyticsV4View.vue'),
    label: 'Analytics (ATC)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-add-to-cart',
  },
  {
    id: 'analytics-v4-email-capture',
    component: () => import('../views/AnalyticsV4View.vue'),
    label: 'Analytics (Email)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-email-capture',
  },
  {
    id: 'analytics-v4-phone-capture',
    component: () => import('../views/AnalyticsV4View.vue'),
    label: 'Analytics (Phone)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'analytics-phone-capture',
  },
  {
    id: 'analytics-empty',
    component: () => import('../views/AnalyticsEmptyView.vue'),
    label: 'Analytics (empty)',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
  },
  {
    id: 'opportunity-detail',
    component: () => import('../views/OptimizationOpportunityDetailView.vue'),
    label: 'Opportunity Detail',
    status: 'active',
    section: null,
    hideLogo: true,
    slug: 'opportunity-detail',
  },
  {
    id: 'opportunities-all',
    component: () => import('../views/OptimizationOpportunitiesAllView.vue'),
    label: 'All Opportunities',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
  },
  {
    id: 'opportunities-all-v2',
    component: () => import('../views/OptimizationOpportunitiesAllV2View.vue'),
    label: 'All Opportunities V2',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
  },
  {
    id: 'opportunities-all-v4',
    component: () => import('../views/OptimizationOpportunitiesAllV4View.vue'),
    label: 'Insights',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
    slug: 'insights',
  },
  {
    id: 'cro-email-template',
    component: () => import('../views/CROEmailTemplateView.vue'),
    label: 'CRO Email Template',
    status: 'active',
    section: 'analytics',
    hideLogo: true,
  },
]

// PPO v2
const ppoViews = [
  {
    id: 'optimize-website',
    component: () => import('../views/OptimizeWebsiteView.vue'),
    label: 'Optimize Website',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'product-page-optimizer',
    component: () => import('../views/ProductPageOptimizerView.vue'),
    label: 'Product Page Optimizer',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-flow',
    component: () => import('../views/PpoCampaignFlowView.vue'),
    label: 'Campaign Flow',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
    slug: 'ppo-campaign-flow',
  },
  {
    id: 'ppo-campaign-flow-v2',
    component: () => import('../views/PpoCampaignFlowV2View.vue'),
    label: 'Campaign Flow (tiles)',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-flow-v3',
    component: () => import('../views/PpoCampaignFlowV3View.vue'),
    label: 'Campaign Flow (cards)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-flow-mvp',
    component: () => import('../views/PpoCampaignFlowMvpView.vue'),
    label: 'Campaign Flow (MVP)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-variable-setup',
    component: () => import('../views/PpoVariableSetupView.vue'),
    label: 'Variable Setup',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
    slug: 'ppo-variable-setup',
  },
  {
    id: 'ppo-campaign-setup-preview',
    component: () => import('../views/PpoCampaignSetupPreviewView.vue'),
    label: 'Setup Preview',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-setup-preview-v2',
    component: () => import('../views/PpoCampaignSetupPreviewV2View.vue'),
    label: 'Setup Preview V2',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-setup-preview-v3',
    component: () => import('../views/PpoCampaignSetupPreviewV3View.vue'),
    label: 'Setup Preview V3',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-generation',
    component: () => import('../views/PpoGenerationView.vue'),
    label: 'Generation',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
    slug: 'ppo-generation',
  },
  {
    id: 'ppo-campaign-detail',
    component: () => import('../views/PpoCampaignDetailView.vue'),
    label: 'Campaign Detail',
    status: 'archived',
    section: null,
    hideLogo: true,
    slug: 'ppo-campaign-detail',
  },
  {
    id: 'ppo-placement',
    component: () => import('../views/PpoCampaignDetailView.vue'),
    label: 'Placement',
    status: 'active',
    section: null,
    hideLogo: true,
    slug: 'ppo-placement',
  },
  {
    id: 'ppo-campaign-detail-v2',
    component: () => import('../views/PpoCampaignDetailV2View.vue'),
    label: 'Campaign Detail V2',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3',
    component: () => import('../views/PpoCampaignDetailV3View.vue'),
    label: 'Campaign Detail V3 (A/B — comparison)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-pivoted',
    component: () => import('../views/PpoCampaignDetailV3View.vue'),
    label: 'Campaign Detail V3 (A/B — pivoted)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-bar-chart',
    component: () => import('../views/PpoCampaignDetailV3View.vue'),
    label: 'Campaign Detail V3 (A/B — bar chart)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-single',
    component: () => import('../views/PpoCampaignDetailV3SingleView.vue'),
    label: 'Campaign Detail V3 (single variant)',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-single-v2',
    component: () => import('../views/PpoCampaignDetailV3SingleV2View.vue'),
    label: 'Campaign Detail V3 (single variant) V2',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-single-v3',
    component: () => import('../views/PpoCampaignDetailV3SingleV3View.vue'),
    label: 'Campaign Detail V3 (single variant) V3',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-single-v4',
    component: () => import('../views/PpoCampaignDetailV3SingleV4View.vue'),
    label: 'Campaign Detail V3 (single variant) V4',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-campaign-detail-v3-single-v5',
    component: () => import('../views/PpoCampaignDetailV3SingleV5View.vue'),
    label: 'Campaign Detail V3 (single variant) V5',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-variant-detail-v1',
    component: () => import('../views/PpoCampaignSetupPreviewView.vue'),
    label: 'Variant Detail',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
  {
    id: 'ppo-variant-detail-v2',
    component: () => import('../views/PpoVariantDetailV2View.vue'),
    label: 'Variant Detail V2',
    status: 'active',
    section: 'ppo',
    hideLogo: true,
  },
]

// PPO V1 (archived)
const ppoV1Views = [
  {
    id: 'ppo-v1-campaign-flow',
    component: () => import('../views/PpoCampaignFlowV1View.vue'),
    label: 'PPO V1',
    status: 'archived',
    section: 'ppoV1',
    hideLogo: true,
  },
  {
    id: 'ppo-v1-variable-setup',
    component: () => import('../views/PpoVariableSetupV1View.vue'),
    label: 'Variable Setup V1',
    status: 'active',
    section: 'ppoV1',
    hideLogo: true,
  },
  {
    id: 'ppo-v1-generation',
    component: () => import('../views/PpoGenerationV1View.vue'),
    label: 'Generation V1',
    status: 'active',
    section: 'ppoV1',
    hideLogo: true,
  },
  {
    id: 'ppo-v1-campaign-detail',
    component: () => import('../views/PpoCampaignDetailV1View.vue'),
    label: 'Campaign Detail V1',
    status: 'active',
    section: 'ppoV1',
    hideLogo: true,
  },
  {
    id: 'ppo-v1-placement',
    component: () => import('../views/PpoCampaignDetailV1View.vue'),
    label: 'Placement V1',
    status: 'active',
    section: 'ppoV1',
    hideLogo: true,
  },
  {
    id: 'ppo-v1-variant-detail-v1',
    component: () => import('../views/PpoVariantDetailV1View.vue'),
    label: 'Variant V1 Detail V1',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'ppo-v1-variant-detail-v2',
    component: () => import('../views/PpoVariantDetailV1View.vue'),
    label: 'Variant V1 Detail V2',
    status: 'active',
    section: null,
    hideLogo: true,
  },
]

// Templates
const templateViews = [
  {
    id: 'templates-v1',
    component: () => import('../views/TemplatesViewV1.vue'),
    label: 'Templates V1',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
  {
    id: 'templates-v2',
    component: () => import('../views/TemplatesViewV2.vue'),
    label: 'Templates',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'templates-v2-essential-theme',
    component: () => import('../views/TemplatesViewV2.vue'),
    label: 'Templates (Essential)',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'templates-v2-branding',
    component: () => import('../views/TemplatesV2BrandingView.vue'),
    label: 'Templates Branding',
    status: 'active',
    section: null,
    hideLogo: true,
  },
  {
    id: 'templates-v3',
    component: () => import('../views/TemplatesViewV3.vue'),
    label: 'Templates V3',
    status: 'archived',
    section: null,
    hideLogo: true,
  },
]

// Image with Badge
const imageViews = [
  {
    id: 'image-with-badge',
    component: () => import('../views/ImageWithBadgeView.vue'),
    label: 'Image Badge V1',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'image-with-badge',
    refName: 'imageWithBadgeRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'image-with-badge' },
  },
  {
    id: 'image-with-badge-v2',
    component: () => import('../views/ImageWithBadgeV2View.vue'),
    label: 'Image Badge V2',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'image-with-badge-v2',
    refName: 'imageWithBadgeRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'image-with-badge' },
  },
  {
    id: 'image-with-badge-v3',
    component: () => import('../views/ImageWithBadgeV3View.vue'),
    label: 'Image Badge V3',
    status: 'active',
    section: null,
    hideLogo: true,
    keyPrefix: 'image-with-badge-v3',
    refName: 'imageWithBadgeRef',
    nav: { sessionReset: true, flowSelected: true, registrationType: 'image-with-badge' },
  },
]

// AI Content (standalone, not in settings)
const aiContentViews = [
  ...generateAiSubViews(
    'ai-texts-images',
    () => import('../views/AiTextsImagesView.vue'),
    'AI Texts & Images',
    'aiContent',
  ),
  ...generateAiSubViews(
    'ai-texts-images-v2',
    () => import('../views/AiTextsImagesV2View.vue'),
    'AI Texts & Images V2',
    'aiContent',
  ),
]

// Settings AI sub-views
const settingsAiViews = [
  ...generateSettingsAiSubViews('settings-ai-texts-images'),
  ...generateSettingsAiSubViews('settings-ai-texts-images-v1'),
  ...generateSettingsAiSubViews('settings-ai-texts-images-v2'),
  {
    id: 'settings-ai-texts-images-v2-feedbacks',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (feedbacks)',
    status: 'archived',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-feedbacks-modal',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (feedbacks modal)',
    status: 'archived',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-next-product',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (next product)',
    status: 'active',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-next-product-ai-input',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (next product · AI input)',
    status: 'active',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-parent-child-product',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (parent · child product)',
    status: 'active',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-credit-buying',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (credit buying)',
    status: 'active',
    section: 'aiContent',
    hideLogo: true,
  },
  {
    id: 'settings-ai-texts-images-v2-ai-input',
    component: () => import('../views/SettingsView.vue'),
    label: 'AI Texts & Images V2 (AI input)',
    status: 'active',
    section: 'aiContent',
    hideLogo: true,
  },
]

// ============================================================================
// Combined export
// ============================================================================
const allViews = [
  ...systemViews,
  ...registrationViews,
  ...homeViews,
  ...wizardViews,
  ...campaignViews,
  ...analyticsViews,
  ...ppoViews,
  ...ppoV1Views,
  ...templateViews,
  ...imageViews,
  ...aiContentViews,
  ...settingsAiViews,
]

// Route namespacing
// ----------------------------------------------------------------------------
// The classic, dashboard-led OptiMonk app lives under an `optimonk/` URL prefix,
// mirroring how the agentic app lives under `agentic/`. This keeps the two
// products unambiguous in the address bar ("which is which"). Every active view
// that belongs to a classic DevNavBar section gets the prefix, except views
// already namespaced under `agentic/`. Navigation is id-based internally, so
// this only changes URLs; bare legacy hashes still resolve via App.vue's
// trailing-segment fallback in getViewFromHash.
// Generated sub-views to archive individually (frozen; moved to the archive dropdown).
const ARCHIVED_IDS = new Set([
  'ai-texts-images-v2-add-products',
  'ai-texts-images-v2-choose-products',
])
for (const def of allViews) {
  if (ARCHIVED_IDS.has(def.id)) def.status = 'archived'
}

const CLASSIC_SECTIONS = new Set([
  'home', 'campaigns', 'campaignPage', 'analytics', 'ppo', 'ppoV1', 'aiContent', 'audience',
])
for (const def of allViews) {
  if (def.status !== 'active') continue
  if (!CLASSIC_SECTIONS.has(def.section)) continue
  const current = def.slug || def.id
  if (current.startsWith('agentic/') || current.startsWith('optimonk/')) continue
  def.slug = `optimonk/${current}`
}

export const viewDefinitions = allViews
